//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class expo
    {
        [Display(Name="ID")]
        public int exp_id { get; set; }
        [Display(Name = "Title")]
        public string exp_title { get; set; }
        [Display(Name = "IMG")]
        public string exp_img { get; set; }
        [Display(Name = "Date")]
        public Nullable<int> exp_date { get; set; }
        [Display(Name = "Discription")]
        public string exp_discription { get; set; }
        [Display(Name = "Owner")]
        public string exp_owner { get; set; }
        [Display(Name = "Status")]
        public string exp_status { get; set; }
    }
}
