//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user_info
    {
        [Display(Name ="ID")]
        public int user_id { get; set; }
        [Display(Name = "E-Mail")]
        public string user_email { get; set; }
        [Display(Name = "Password")]
        public string user_password { get; set; }
        [Display(Name = "Age")]
        public Nullable<int> user_age { get; set; }
        [Display(Name = "Address")]
        public string user_address { get; set; }
        [Display(Name = "category")]
        public string user_category { get; set; }
        [Display(Name = "Name")]
        public string user_name { get; set; }
        [Display(Name = "IMG")]
        public string user_img { get; set; }
    }
}
